### ISSUE TITLE
有个下标越界异常，请帮忙看下

### ISSUE THREAD

**Issue by listen-zhou** [rolandhe/hiriver#9]
2020-01-20 15:23:02.489 [Provider-channel_000021] INFO  c.h.u.m.l.TextProtocolBlockingTransportImpl - handshake success.
2020-01-20 15:23:02.489 [Provider-channel_000021] INFO  c.h.u.m.l.TextProtocolBlockingTransportImpl - init SQL:SET AUTOCOMMIT=1
2020-01-20 15:23:02.493 [Provider-channel_000021] INFO  c.h.c.s.impl.DefaultChannelStream - channelId is channel_0000,meet unknown error.
java.lang.IndexOutOfBoundsException: Index: 5, Size: 5
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at com.hiriver.unbiz.mysql.lib.protocol.binlog.TableMeta.getColumnDefinition(TableMeta.java:38)
	at com.hiriver.unbiz.mysql.lib.protocol.binlog.event.BaseRowEvent.parseRow(BaseRowEvent.java:175)
	at com.hiriver.unbiz.mysql.lib.protocol.binlog.event.BaseRowEvent.parse(BaseRowEvent.java:151)
	at com.hiriver.unbiz.mysql.lib.BinlogStreamBlockingTransportImpl.readEvent(BinlogStreamBlockingTransportImpl.java:363)
	at com.hiriver.unbiz.mysql.lib.BinlogStreamBlockingTransportImpl.getBinlogOutputImmediately(BinlogStreamBlockingTransportImpl.java:256)
	at com.hiriver.streamsource.impl.MysqlStreamSource.readValidInfo(MysqlStreamSource.java:49)
	at com.hiriver.channel.stream.impl.DefaultChannelStream.providerThreadCore(DefaultChannelStream.java:247)
	at com.hiriver.channel.stream.impl.DefaultChannelStream.access$0(DefaultChannelStream.java:234)
	at com.hiriver.channel.stream.impl.DefaultChannelStream$2.run(DefaultChannelStream.java:216)
	at java.lang.Thread.run(Thread.java:745)
2020-01-20 15:23:02.493 [Provider-channel_000021] INFO  c.h.c.s.impl.DefaultChannelStream - load binlog position mysql-bin.000129:345714582 from mem,channelId is channel_0000.

**Comment by rolandhe** [comment]
发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 周梦强 <notifications@github.com&gt;
发送时间: 2020年1月20日 15:41
收件人: rolandhe/hiriver <hiriver@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[rolandhe/hiriver] 有个下标越界异常，请帮忙看下 (#9)


能复现吗？什么类型的数据？

2020-01-20 15:23:02.489 [Provider-channel_000021] INFO  c.h.u.m.l.TextProtocolBlockingTransportImpl - handshake success.
 2020-01-20 15:23:02.489 [Provider-channel_000021] INFO  c.h.u.m.l.TextProtocolBlockingTransportImpl - init SQL:SET AUTOCOMMIT=1
 2020-01-20 15:23:02.493 [Provider-channel_000021] INFO  c.h.c.s.impl.DefaultChannelStream - channelId is channel_0000,meet unknown error.
 java.lang.IndexOutOfBoundsException: Index: 5, Size: 5
 at java.util.ArrayList.rangeCheck(ArrayList.java:653)
 at java.util.ArrayList.get(ArrayList.java:429)
 at com.hiriver.unbiz.mysql.lib.protocol.binlog.TableMeta.getColumnDefinition(TableMeta.java:38)
 at com.hiriver.unbiz.mysql.lib.protocol.binlog.event.BaseRowEvent.parseRow(BaseRowEvent.java:175)
 at com.hiriver.unbiz.mysql.lib.protocol.binlog.event.BaseRowEvent.parse(BaseRowEvent.java:151)
 at com.hiriver.unbiz.mysql.lib.BinlogStreamBlockingTransportImpl.readEvent(BinlogStreamBlockingTransportImpl.java:363)
 at com.hiriver.unbiz.mysql.lib.BinlogStreamBlockingTransportImpl.getBinlogOutputImmediately(BinlogStreamBlockingTransportImpl.java:256)
 at com.hiriver.streamsource.impl.MysqlStreamSource.readValidInfo(MysqlStreamSource.java:49)
 at com.hiriver.channel.stream.impl.DefaultChannelStream.providerThreadCore(DefaultChannelStream.java:247)
 at com.hiriver.channel.stream.impl.DefaultChannelStream.access$0(DefaultChannelStream.java:234)
 at com.hiriver.channel.stream.impl.DefaultChannelStream$2.run(DefaultChannelStream.java:216)
 at java.lang.Thread.run(Thread.java:745)
 2020-01-20 15:23:02.493 [Provider-channel_000021] INFO  c.h.c.s.impl.DefaultChannelStream - load binlog position mysql-bin.000129:345714582 from mem,channelId is channel_0000.
